name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle executables
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: .gradle-wrapper-${{ hashFiles('gradle/**') }}
      - name: Cache Java dependencies
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/cache
          key: .gradle-cache-${{ hashFiles('build.gradle') }}
      - name: Gradle Build
        run: ./gradlew assemble
