name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .NET dependencies
        uses: actions/cache@v1.1.0
        with:
          path: ~/.nuget
          key: .nuget-${{ hashFiles('src/dotnet/**/*.csproj') }}+${{ hashFiles('src/dotnet/**/*.props') }}
      - name: Cache Gradle executables
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: .gradle-wrapper-${{ hashFiles('gradle/**') }}
      - name: Cache Java dependencies
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: .gradle-caches-${{ hashFiles('build.gradle') }}
      - name: Build Backend
        run: powershell -ExecutionPolicy Bypass -File ./buildPlugin.ps1
      - name: Build Frontend
        run: ./gradlew --no-daemon assemble
      - name: Test
        run: ./gradlew --no-daemon test
