name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Backend
      - name: NuGet Cache
        uses: actions/cache@v1.1.0
        with:
          path: ~/.nuget
          key: .nuget-${{ hashFiles('src/dotnet/**/*.csproj') }}+${{ hashFiles('src/dotnet/**/*.props') }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.101'
      - name: Build Backend
        run: dotnet build -c Release

      # Frontend
      - name: Gradle Wrapper Cache
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/wrapper
          key: .gradle-wrapper-${{ hashFiles('gradle/**') }}
      - name: Gradle Cache
        uses: actions/cache@v1.1.0
        with:
          path: ~/.gradle/caches
          key: .gradle-caches-${{ hashFiles('**/*.gradle') }}
      - name: Test
        run: ./gradlew -PBuildConfiguration=Release --no-daemon test
      - name: Upload Test Results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-results
          path: build/reports/tests

      # Distribution
      - name: Build Distribution
        run: ./gradlew -PBuildConfiguration=Release --no-daemon buildPlugin
      - name: Upload Distribution
        uses: actions/upload-artifact@v1.0.0
        with:
          name: distribution
          path: build/distributions
